### ISSUE TITLE
Duplicate rule?

### ISSUE THREAD

**Issue by Eroc33** [ronsavage/SQL#2]
At https://github.com/ronsavage/SQL/blob/master/sql-2003-2.bnf#L1344-L1346 `<path-resolved user-defined type name>` seems to be duplicated

Edit:
Also `<character set specification list>` at [L4491](https://github.com/ronsavage/SQL/blob/c3f74e70e0a6d6af1b9a3cfca6a746362f6c3e07/sql-2003-2.bnf#L4491) and [L5307](https://github.com/ronsavage/SQL/blob/c3f74e70e0a6d6af1b9a3cfca6a746362f6c3e07/sql-2003-2.bnf#L5307)
and `<item number>` at [L5422](https://github.com/ronsavage/SQL/blob/master/sql-2003-2.bnf#L5422) and [L5356](https://github.com/ronsavage/SQL/blob/master/sql-2003-2.bnf#L5356)

**Comment by jleffler** [comment]
I've fixed the headline problem with commit 84842e6.  I've only just read the issue in full and hence didn't previously see the other two repetitions (which are subtler — the entries are further apart in the source) so I still need to fix those.  This issue is still active, therefore.

Thanks for the bug report, Euan.

**Comment by jleffler** [comment]
Fix the other repeated rule problems, and upgrade the bnf2html.pl script so it spots them automatically.  Also strip trailing blanks.

Thank you, Euan, for the bug report, and I'm sorry it took so long to complete the changes.
